// <auto-generated />
using System;
using Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Backend.Migrations
{
    [DbContext(typeof(RasporedPacijenataContext))]
    [Migration("20210313143202_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Backend.Models.Klinike", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrojLekara")
                        .HasColumnType("int")
                        .HasColumnName("BrojLekara");

                    b.Property<int>("BrojTermina")
                        .HasColumnType("int")
                        .HasColumnName("Termina");

                    b.Property<string>("Naziv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Naziv");

                    b.HasKey("ID");

                    b.ToTable("PrivatneKlinike");
                });

            modelBuilder.Entity("Backend.Models.Lekar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ime");

                    b.Property<int?>("KlinikeID")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Prezime");

                    b.Property<string>("Specijalizacija")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Specijalizacija");

                    b.HasKey("ID");

                    b.HasIndex("KlinikeID");

                    b.ToTable("Lekar");
                });

            modelBuilder.Entity("Backend.Models.Rasporedi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ime");

                    b.Property<int>("JMBG")
                        .HasColumnType("int")
                        .HasColumnName("JMBG");

                    b.Property<int?>("KlinikeID")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Prezime");

                    b.Property<string>("TipBoja")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TipBoja");

                    b.Property<int>("X")
                        .HasColumnType("int")
                        .HasColumnName("X");

                    b.Property<int>("Y")
                        .HasColumnType("int")
                        .HasColumnName("Y");

                    b.HasKey("ID");

                    b.HasIndex("KlinikeID");

                    b.ToTable("Rasporedi");
                });

            modelBuilder.Entity("Backend.Models.Lekar", b =>
                {
                    b.HasOne("Backend.Models.Klinike", "Klinike")
                        .WithMany("Lekari")
                        .HasForeignKey("KlinikeID");

                    b.Navigation("Klinike");
                });

            modelBuilder.Entity("Backend.Models.Rasporedi", b =>
                {
                    b.HasOne("Backend.Models.Klinike", "Klinike")
                        .WithMany("Rasporedi")
                        .HasForeignKey("KlinikeID");

                    b.Navigation("Klinike");
                });

            modelBuilder.Entity("Backend.Models.Klinike", b =>
                {
                    b.Navigation("Lekari");

                    b.Navigation("Rasporedi");
                });
#pragma warning restore 612, 618
        }
    }
}
